---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: concourse-k8s-cleaner-account
  namespace: default

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: concourse-k8s-cleaner-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: concourse-k8s-cleaner-account
  namespace: default
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: ""