---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: concourse-k8s-cleaner-account
  namespace: devops-tools

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: concourse-k8s-cleaner-rolebinding
subjects:
- kind: ServiceAccount
  name: concourse-k8s-cleaner-account
  namespace: devops-tools
roleRef:
  kind: Role
  name: concourse-k8s-cleaner-role
  apiGroup: ""

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: concourse-k8s-cleaner-role
  namespace: devops-tools
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "create", "delete"]